/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.12 and Signal Processing Toolbox 9.0.
 * Generated on: 08-Apr-2022 15:10:03
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II, Second-Order Sections
 * Number of Sections  : 2
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "types.hpp"
/* 
 * Expected path to tmwtypes.h 
 * /Applications/MATLAB_R2022a.app/extern/include/tmwtypes.h 
 */
#define MWSPT_NSEC 5
[[maybe_unused]]constexpr nerv::usize NL[MWSPT_NSEC] = { 1,3,1,3,1 };
[[maybe_unused]]constexpr nerv::f64 NUM[MWSPT_NSEC][3] = {
  {
     0.8734299512416,                 0,                 0 
  },
  {
                   1,                -2,                 1 
  },
  {
     0.7604867746921,                 0,                 0 
  },
  {
                   1,                -2,                 1 
  },
  {
                   1,                 0,                 0 
  }
};
[[maybe_unused]]constexpr nerv::usize DL[MWSPT_NSEC] = { 1,3,1,3,1 };
[[maybe_unused]]constexpr nerv::f64 DEN[MWSPT_NSEC][3] = {
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.703750771144,   0.7899690338225 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.483438857329,   0.5585082414397 
  },
  {
                   1,                 0,                 0 
  }
};
