/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.12 and Signal Processing Toolbox 9.0.
 * Generated on: 08-Apr-2022 16:59:12
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II
 * Numerator Length    : 5
 * Denominator Length  : 5
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "types.hpp"
/* 
 * Expected path to tmwtypes.h 
 * /Applications/MATLAB_R2022a.app/extern/include/tmwtypes.h 
 */
[[maybe_unused]]constexpr nerv::usize NL = 5;
[[maybe_unused]]constexpr nerv::f64 NUM[5] = {
     0.6642319265392,   -2.656927706157,    3.985391559235,   -2.656927706157,
     0.6642319265392
};
[[maybe_unused]]constexpr nerv::usize DL = 5;
[[maybe_unused]]constexpr nerv::f64 DEN[5] = {
                   1,   -3.187189628473,    3.875887372381,   -2.123429607902,
      0.441204215872
};
